name: medkenes
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase — стабильные версии (ноябрь 2025)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  cloud_functions: ^5.1.3
  http: ^1.2.2
  # Остальное
  flutter_tts: ^4.0.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1
  url_launcher: ^6.3.0
  speech_to_text: ^7.0.0
  uuid: ^4.5.0
  intl: ^0.20.2              # ← ВЕРНУЛ 0.20.2 — это обязательно!
  bubble: ^1.2.1
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  vibration: ^1.8.4


  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-VariableFont_wght.ttf
          weight: 700

  assets:
    - assets/avatar.png
    - assets/doctor.png
    - assets/ambulance_small.png
    - assets/ambulance_v2.png
    - assets/ambulance_v3.png